apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: policydecisions.operator.ibm.com
  labels:
    app.kubernetes.io/instance: ibm-iam-operator
    app.kubernetes.io/managed-by: ibm-iam-operator
    app.kubernetes.io/name: ibm-iam-operator
spec:
  group: operator.ibm.com
  names:
    kind: PolicyDecision
    listKind: PolicyDecisionList
    plural: policydecisions
    singular: policydecision
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: PolicyDecision is the Schema for the policydecisions API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PolicyDecisionSpec defines the desired state of PolicyDecision
          properties:
            auditService:
              properties:
                imageName:
                  type: string
                imageRegistry:
                  type: string
                imageTag:
                  type: string
                journalPath:
                  type: string
              required:
              - imageName
              - imageRegistry
              - imageTag
              - journalPath
              type: object
            imageName:
              type: string
            imageRegistry:
              type: string
            imageTag:
              type: string
            initMongodb:
              properties:
                imageName:
                  type: string
                imageRegistry:
                  type: string
                imageTag:
                  type: string
              required:
              - imageName
              - imageRegistry
              - imageTag
              type: object
            operatorVersion:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            replicas:
              format: int32
              type: integer
          required:
          - auditService
          - imageName
          - imageRegistry
          - imageTag
          - initMongodb
          - operatorVersion
          - replicas
          type: object
        status:
          description: PolicyDecisionStatus defines the observed state of PolicyDecision
          properties:
            nodes:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                type: string
              type: array
          required:
          - nodes
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
