apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: securityonboardings.operator.ibm.com
spec:
  group: operator.ibm.com
  names:
    kind: SecurityOnboarding
    listKind: SecurityOnboardingList
    plural: securityonboardings
    singular: securityonboarding
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: SecurityOnboarding is the Schema for the securityonboardings API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SecurityOnboardingSpec defines the desired state of SecurityOnboarding
          properties:
            iamOnboarding:
              properties:
                imageName:
                  type: string
                imageRegistry:
                  type: string
                imageTag:
                  type: string
              required:
              - imageName
              - imageRegistry
              - imageTag
              type: object
            imageName:
              type: string
            imageRegistry:
              type: string
            imageTag:
              type: string
            impersonation:
              properties:
                enableImpersonation:
                  type: boolean
              required:
              - enableImpersonation
              type: object
            initAuthService:
              properties:
                imageName:
                  type: string
                imageRegistry:
                  type: string
                imageTag:
                  type: string
              required:
              - imageName
              - imageRegistry
              - imageTag
              type: object
            initIdentityManager:
              properties:
                imageName:
                  type: string
                imageRegistry:
                  type: string
                imageTag:
                  type: string
              required:
              - imageName
              - imageRegistry
              - imageTag
              type: object
            initIdentityProvider:
              properties:
                imageName:
                  type: string
                imageRegistry:
                  type: string
                imageTag:
                  type: string
              required:
              - imageName
              - imageRegistry
              - imageTag
              type: object
            initPAPSpec:
              properties:
                imageName:
                  type: string
                imageRegistry:
                  type: string
                imageTag:
                  type: string
              required:
              - imageName
              - imageRegistry
              - imageTag
              type: object
            initTokenService:
              properties:
                imageName:
                  type: string
                imageRegistry:
                  type: string
                imageTag:
                  type: string
              required:
              - imageName
              - imageRegistry
              - imageTag
              type: object
            operatorVersion:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            replicas:
              format: int32
              type: integer
          required:
          - iamOnboarding
          - imageName
          - imageRegistry
          - imageTag
          - impersonation
          - initAuthService
          - initIdentityManager
          - initIdentityProvider
          - initPAPSpec
          - initTokenService
          - operatorVersion
          - replicas
          type: object
        status:
          description: SecurityOnboardingStatus defines the observed state of SecurityOnboarding
          properties:
            podNames:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                type: string
              type: array
          required:
          - podNames
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
