apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/instance: ibm-iam-operator
    app.kubernetes.io/managed-by: ibm-iam-operator
    app.kubernetes.io/name: ibm-iam-operator
<<<<<<< HEAD
    component-id: {{ .Chart.Name }}
=======
>>>>>>> 94ea2d4f7e08d174851119624a48a0f2c1af013b
  name: ibm-iam-operator
  namespace: {{.Values.global.operatorNamespace}}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ibm-iam-operator
subjects:
- kind: ServiceAccount
  name: ibm-iam-operator
  namespace: {{.Values.global.operatorNamespace}}