# permissions for end users to view authentications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: authentication-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: ibm-iam-operator
    app.kubernetes.io/part-of: ibm-iam-operator
    app.kubernetes.io/managed-by: kustomize
  name: authentication-viewer-role
rules:
- apiGroups:
  - operator.ibm.com
  resources:
  - authentications
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operator.ibm.com
  resources:
  - authentications/status
  verbs:
  - get
