resources:
- ../../bases
generatorOptions:
  disableNameSuffixHash: true
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- path: ./image_env_vars_patch.yaml
  target:
    group: apps
    kind: Deployment
    name: ibm-iam-operator
    version: v1
images:
- name: controller
  newName: docker-na-public.artifactory.swg-devops.com/hyc-cloud-private-scratch-docker-local/rwhundle/ibm-iam-operator
  newTag: latest
