apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clients.oidc.security.ibm.com
spec:
  group: oidc.security.ibm.com
  names:
    kind: Client
    listKind: ClientList
    plural: clients
    singular: client
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: Client is the Schema for the clients API
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: ClientSpec defines the desired state of Client
            properties:
              clientId:
                type: string
              oidcLibertyClient:
                description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                  Important: Run "operator-sdk generate k8s" to regenerate code after
                  modifying this file Add custom validation using kubebuilder tags:
                  https://book.kubebuilder.io/beyond_basics/generating_crd.html'
                properties:
                  post_logout_redirect_uris:
                    items:
                      type: string
                    type: array
                  redirect_uris:
                    description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of
                      cluster Important: Run "operator-sdk generate k8s" to regenerate
                      code after modifying this file Add custom validation using kubebuilder
                      tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html'
                    items:
                      type: string
                    type: array
                  trusted_uri_prefixes:
                    items:
                      type: string
                    type: array
                required:
                - post_logout_redirect_uris
                - redirect_uris
                - trusted_uri_prefixes
                type: object
              secret:
                type: string
              zenInstanceId:
                type: string
              zenProductNameUrl:
                type: string
            required:
            - oidcLibertyClient
            - secret
            type: object
          status:
            description: ClientStatus defines the observed state of Client
            properties:
              conditions:
                items:
                  description: CertificateCondition contains condition information
                    for an Certificate.
                  properties:
                    lastTransitionTime:
                      description: LastTransitionTime is the timestamp corresponding
                        to the last status change of this condition.
                      format: date-time
                      type: string
                    message:
                      description: Message is a human readable description of the
                        details of the last transition, complementing reason.
                      type: string
                    reason:
                      description: Reason is a brief machine readable explanation
                        for the condition's last transition.
                      type: string
                    status:
                      description: Status of the condition, one of ('True', 'False',
                        'Unknown').
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      description: Type of the condition, currently ('Ready').
                      type: string
                  required:
                  - status
                  - type
                  type: object
                type: array
              lastFailureTime:
                format: date-time
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
