apiVersion: operator.ibm.com/v1alpha1
kind: SecretWatcher
metadata:
  name: secretwatcher-deployment
  labels:
    app.kubernetes.io/instance: ibm-iam-operator
    app.kubernetes.io/managed-by: ibm-iam-operator
    app.kubernetes.io/name: ibm-iam-operator
spec:
  config:
    excludeOperand: false
  operatorVersion: "0.14.1"
  imageRegistry: "quay.io/opencloudio/icp-secret-watcher"
  imageTagPostfix: "3.5.0"
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 64Mi
  replicas: 1
