apiVersion: operator.ibm.com/v1alpha1
kind: SecretWatcher
metadata:
  name: secretwatcher-deployment
spec:
  operatorVersion: "0.14.1"
  imageName: "icp-secret-watcher"
  imageRegistry: "quay.io/opencloudio"
  imageTagPostfix: "3.3.1"
  replicas: 1