apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: paps.operator.ibm.com
spec:
  group: operator.ibm.com
  names:
    kind: Pap
    listKind: PapList
    plural: paps
    singular: pap
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Pap is the Schema for the paps API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PapSpec defines the desired state of Pap
          properties:
            auditService:
              properties:
                imageName:
                  type: string
                imageRegistry:
                  type: string
                imageTag:
                  type: string
                journalPath:
                  type: string
              required:
              - imageName
              - imageRegistry
              - imageTag
              - journalPath
              type: object
            operatorVersion:
              description: 'INSERT ADDITIONAL SPEC FIELDS - desired state of cluster
                Important: Run "operator-sdk generate k8s" to regenerate code after
                modifying this file Add custom validation using kubebuilder tags:
                https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              type: string
            papService:
              description: PapServiceSpec defined the desired state of PapService
                Container
              properties:
                imageName:
                  type: string
                imageRegistry:
                  type: string
                imageTag:
                  type: string
              required:
              - imageName
              - imageRegistry
              - imageTag
              type: object
            replicas:
              format: int32
              type: integer
          required:
          - auditService
          - operatorVersion
          - papService
          - replicas
          type: object
        status:
          description: PapStatus defines the observed state of Pap
          properties:
            nodes:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book-v1.book.kubebuilder.io/beyond_basics/generating_crd.html'
              items:
                type: string
              type: array
          required:
          - nodes
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
