apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: paps.operator.ibm.com
spec:
  group: operator.ibm.com
  names:
    kind: Pap
    listKind: PapList
    plural: paps
    singular: pap
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: Pap is the Schema for the paps API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: PapSpec defines the desired state of Pap
          type: object
        status:
          description: PapStatus defines the observed state of Pap
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
