apiVersion: operator.ibm.com/v1alpha1
kind: SecretWatcher
metadata:
  name: secretwatcher-deployment
  labels:
    app.kubernetes.io/instance: ibm-iam-operator
    app.kubernetes.io/managed-by: ibm-iam-operator
    app.kubernetes.io/name: ibm-iam-operator
spec:
  operatorVersion: "0.14.1"
  imageName: "icp-secret-watcher"
  imageRegistry: "quay.io/opencloudio"
  imageTagPostfix: "3.3.2"
  replicas: 1
