apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-iam-operator
  labels:
    app.kubernetes.io/instance: ibm-iam-operator
    app.kubernetes.io/managed-by: ibm-iam-operator
    app.kubernetes.io/name: ibm-iam-operator

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-iam-operand-restricted
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.first: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"common-web-ui-callback"}}'
  labels:
    app.kubernetes.io/instance: ibm-iam-operator
    app.kubernetes.io/managed-by: ibm-iam-operator
    app.kubernetes.io/name: ibm-iam-operator
