apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-iam-operator
  labels:
    app.kubernetes.io/instance: ibm-iam-operator
    app.kubernetes.io/managed-by: ibm-iam-operator
    app.kubernetes.io/name: ibm-iam-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-iam-operand-privileged
  labels:
    app.kubernetes.io/instance: ibm-iam-operator
    app.kubernetes.io/managed-by: ibm-iam-operator
    app.kubernetes.io/name: ibm-iam-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ibm-iam-operand-restricted
  labels:
    app.kubernetes.io/instance: ibm-iam-operator
    app.kubernetes.io/managed-by: ibm-iam-operator
    app.kubernetes.io/name: ibm-iam-operator
