## Append samples you want in your CSV to this file as resources ##
resources:
- ../../bases
#+kubebuilder:scaffold:manifestskustomizesamples

patches:
- path: authentication_image_patch.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
