## Append samples you want in your CSV to this file as resources ##
resources:
- operator_v1alpha1_authentication.yaml
#+kubebuilder:scaffold:manifestskustomizesamples

patchesStrategicMerge:
- authentication_image_patch.yaml
