apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ibm-iam-operator-{{ .Values.global.operatorNamespace }}
  namespace: {{ .Values.global.operatorNamespace }}
  labels:
    app.kubernetes.io/instance: ibm-iam-operator
    app.kubernetes.io/managed-by: ibm-iam-operator
    app.kubernetes.io/name: ibm-iam-operator
    component-id: {{ .Chart.Name }}
    {{- if .Values.cpfs }}
      {{- if .Values.cpfs.labels }}
        {{- with .Values.cpfs.labels }}
          {{- toYaml . | nindent 4 }}
        {{- end }}
      {{- end }}
      {{- if .Values.cpfs.clusterLabels }}
        {{- with .Values.cpfs.clusterLabels }}
          {{- toYaml . | nindent 4 }}
        {{- end }}
      {{- end }}
    {{- end }}
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - create
- apiGroups:
  - user.openshift.io
  resources:
  - users
  - groups
  - identities
  verbs:
  - get
  - list
