apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibm-iam-operator-{{ .Values.global.operatorNamespace }}
  labels:
    component-id: {{ .Chart.Name }}
    {{- if .Values.cpfs }}
      {{- if .Values.cpfs.labels }}
        {{- with .Values.cpfs.labels }}
          {{- toYaml . | nindent 4 }}
        {{- end }}
      {{- end }}
      {{- if .Values.cpfs.clusterLabels }}
        {{- with .Values.cpfs.clusterLabels }}
          {{- toYaml . | nindent 4 }}
        {{- end }}
      {{- end }}
    {{- end }}
subjects:
- kind: ServiceAccount
  name: ibm-iam-operator
  namespace: {{ .Values.global.operatorNamespace }}
roleRef:
    kind: ClusterRole
    name: ibm-iam-operator-{{ .Values.global.operatorNamespace }}
    apiGroup: rbac.authorization.k8s.io
