apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ibm-iam-operator
subjects:
- kind: ServiceAccount
  name: ibm-iam-operator
  namespace: '{{.Release.Namespace}}'
roleRef:
    kind: ClusterRole
    name: ibm-iam-operator
    apiGroup: rbac.authorization.k8s.io
